# Generated by Django 4.1.1 on 2022-11-15 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_contractno_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='minute',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='این مقدار باید ۰ تا ۶۰ باشد'), django.core.validators.MaxValueValidator(60, message='این مقدار باید ۰ تا ۶۰ باشد')]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='second',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='این مقدار باید ۰ تا ۶۰ باشد'), django.core.validators.MaxValueValidator(60, message='این مقدار باید ۰ تا ۶۰ باشد')]),
        ),
    ]
